import type { ErrorCode } from '../errors/codes.ts';
import { UPDATE_AGENT_BODY_KEYS, updateAgentBodySchema } from './agents.ts';
import {
	START_BATCH_BODY_KEYS,
	WRAPUP_BATCH_BODY_KEYS,
	startBatchBodySchema,
	wrapupBatchBodySchema,
} from './batches.ts';
import {
	CREATE_DOCUMENT_BODY_KEYS,
	UPDATE_DOCUMENT_SETTINGS_BODY_KEYS,
	createDocumentBodySchema,
	updateDocumentSettingsBodySchema,
} from './documents.ts';
import { DECIDE_GATE_BODY_KEYS, decideGateBodySchema } from './gates.ts';
import { CLAIM_PAIRING_CODE_BODY_KEYS, claimPairingCodeBodySchema } from './pair.ts';
import {
	ABORT_RUN_BODY_KEYS,
	CREATE_RUN_BODY_KEYS,
	CREATE_RUN_MESSAGE_BODY_KEYS,
	RERUN_RUN_BODY_KEYS,
	abortRunBodySchema,
	createRunBodySchema,
	createRunMessageBodySchema,
	rerunRunBodySchema,
} from './runs.ts';
import { UPDATE_GATE_SETTINGS_BODY_KEYS, updateGateSettingsBodySchema } from './settings.ts';

export interface RouteDefinition {
	readonly method: 'GET' | 'POST' | 'DELETE' | 'PATCH';
	readonly path: string;
	readonly auth: 'device' | 'none';
	readonly reqType: string;
	readonly resType: string;
	readonly errors: readonly ErrorCode[];
	readonly bodySchema?: Record<string, unknown>;
	readonly bodyKeys?: readonly string[];
}

export const REQUEST_BODY_SCHEMAS = [
	{
		name: 'claimPairingCode',
		path: '/api/v1/pair/claim',
		method: 'POST' as const,
		schema: claimPairingCodeBodySchema,
		keys: CLAIM_PAIRING_CODE_BODY_KEYS,
	},
	{
		name: 'createDocument',
		path: '/api/v1/documents',
		method: 'POST' as const,
		schema: createDocumentBodySchema,
		keys: CREATE_DOCUMENT_BODY_KEYS,
	},
	{
		name: 'updateDocumentSettings',
		path: '/api/v1/documents/:docId/settings',
		method: 'PATCH' as const,
		schema: updateDocumentSettingsBodySchema,
		keys: UPDATE_DOCUMENT_SETTINGS_BODY_KEYS,
	},
	{
		name: 'startBatch',
		path: '/api/v1/batches/:batchId/start',
		method: 'POST' as const,
		schema: startBatchBodySchema,
		keys: START_BATCH_BODY_KEYS,
	},
	{
		name: 'wrapupBatch',
		path: '/api/v1/batches/:batchId/wrapup',
		method: 'POST' as const,
		schema: wrapupBatchBodySchema,
		keys: WRAPUP_BATCH_BODY_KEYS,
	},
	{
		name: 'updateAgent',
		path: '/api/v1/agents/:agentId',
		method: 'PATCH' as const,
		schema: updateAgentBodySchema,
		keys: UPDATE_AGENT_BODY_KEYS,
	},
	{
		name: 'createRun',
		path: '/api/v1/runs',
		method: 'POST' as const,
		schema: createRunBodySchema,
		keys: CREATE_RUN_BODY_KEYS,
	},
	{
		name: 'abortRun',
		path: '/api/v1/runs/:runId/abort',
		method: 'POST' as const,
		schema: abortRunBodySchema,
		keys: ABORT_RUN_BODY_KEYS,
	},
	{
		name: 'rerunRun',
		path: '/api/v1/runs/:runId/rerun',
		method: 'POST' as const,
		schema: rerunRunBodySchema,
		keys: RERUN_RUN_BODY_KEYS,
	},
	{
		name: 'createRunMessage',
		path: '/api/v1/runs/:runId/messages',
		method: 'POST' as const,
		schema: createRunMessageBodySchema,
		keys: CREATE_RUN_MESSAGE_BODY_KEYS,
	},
	{
		name: 'decideGate',
		path: '/api/v1/gates/:gateId/decide',
		method: 'POST' as const,
		schema: decideGateBodySchema,
		keys: DECIDE_GATE_BODY_KEYS,
	},
	{
		name: 'updateGateSettings',
		path: '/api/v1/settings/gates',
		method: 'PATCH' as const,
		schema: updateGateSettingsBodySchema,
		keys: UPDATE_GATE_SETTINGS_BODY_KEYS,
	},
] as const;

export const ROUTES: readonly RouteDefinition[] = [
	{
		method: 'GET',
		path: '/api/v1/health',
		auth: 'none',
		reqType: 'void',
		resType: 'HealthDiagnostics',
		errors: ['E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/version',
		auth: 'none',
		reqType: 'void',
		resType: 'VersionResponse',
		errors: ['E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/pair/claim',
		auth: 'none',
		reqType: 'ClaimPairingCodeBody',
		resType: 'ClaimPairingCodeResponse',
		errors: ['E_VALIDATION', 'E_PAIRING_CODE_INVALID', 'E_RATE_LIMITED', 'E_INTERNAL'],
		bodySchema: claimPairingCodeBodySchema,
		bodyKeys: CLAIM_PAIRING_CODE_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/pair/code',
		auth: 'device',
		reqType: 'void',
		resType: 'CreatePairingCodeResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_RATE_LIMITED', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/devices',
		auth: 'device',
		reqType: 'void',
		resType: 'ListDevicesResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'DELETE',
		path: '/api/v1/devices/:deviceId',
		auth: 'device',
		reqType: 'void',
		resType: 'RevokeDeviceResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/documents',
		auth: 'device',
		reqType: 'void',
		resType: 'ListDocumentsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/documents',
		auth: 'device',
		reqType: 'CreateDocumentBody',
		resType: 'CreateDocumentResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_VALIDATION',
			'E_DOC_SOURCE_UNREADABLE',
			'E_INTERNAL',
		],
		bodySchema: createDocumentBodySchema,
		bodyKeys: CREATE_DOCUMENT_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/documents/:docId/refresh',
		auth: 'device',
		reqType: 'void',
		resType: 'RefreshDocumentResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_DOC_SOURCE_UNREADABLE',
			'E_INTERNAL',
		],
	},
	{
		method: 'POST',
		path: '/api/v1/documents/:docId/open-reader',
		auth: 'device',
		reqType: 'void',
		resType: 'OpenReaderResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'PATCH',
		path: '/api/v1/documents/:docId/settings',
		auth: 'device',
		reqType: 'UpdateDocumentSettingsBody',
		resType: 'UpdateDocumentSettingsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_VALIDATION', 'E_INTERNAL'],
		bodySchema: updateDocumentSettingsBodySchema,
		bodyKeys: UPDATE_DOCUMENT_SETTINGS_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/documents/:docId/tasks',
		auth: 'device',
		reqType: 'void',
		resType: 'ListDocumentTasksResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/documents/:docId/batches',
		auth: 'device',
		reqType: 'void',
		resType: 'ListDocumentBatchesResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/batches/:batchId/start',
		auth: 'device',
		reqType: 'StartBatchBody',
		resType: 'StartBatchResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_VALIDATION', 'E_INTERNAL'],
		bodySchema: startBatchBodySchema,
		bodyKeys: START_BATCH_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/batches/:batchId/pause',
		auth: 'device',
		reqType: 'void',
		resType: 'PauseBatchResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/batches/:batchId/wrapup',
		auth: 'device',
		reqType: 'WrapupBatchBody',
		resType: 'WrapupBatchResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_VALIDATION',
			'E_RUN_ALREADY_EXISTS',
			'E_BATCH_NOT_WRAPPABLE',
			'E_WRAPUP_ROUND_LIMIT',
			'E_AGENT_UNAVAILABLE',
			'E_INTERNAL',
		],
		bodySchema: wrapupBatchBodySchema,
		bodyKeys: WRAPUP_BATCH_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/batches/:batchId/wrapups',
		auth: 'device',
		reqType: 'void',
		resType: 'GetBatchWrapupsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/agents',
		auth: 'device',
		reqType: 'void',
		resType: 'ListAgentsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'PATCH',
		path: '/api/v1/agents/:agentId',
		auth: 'device',
		reqType: 'UpdateAgentBody',
		resType: 'UpdateAgentResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_VALIDATION', 'E_INTERNAL'],
		bodySchema: updateAgentBodySchema,
		bodyKeys: UPDATE_AGENT_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/agents/:agentId/probe',
		auth: 'device',
		reqType: 'void',
		resType: 'ProbeAgentResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_AGENT_UNAVAILABLE',
			'E_AGENT_VERSION_UNRECOGNIZED',
			'E_INTERNAL',
		],
	},
	{
		method: 'GET',
		path: '/api/v1/agents/:agentId/models',
		auth: 'device',
		reqType: 'void',
		resType: 'ListAgentModelsResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_AGENT_UNAVAILABLE',
			'E_INTERNAL',
		],
	},
	{
		method: 'POST',
		path: '/api/v1/runs',
		auth: 'device',
		reqType: 'CreateRunBody',
		resType: 'CreateRunResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_VALIDATION',
			'E_RUN_ALREADY_EXISTS',
			'E_AGENT_UNAVAILABLE',
			'E_AGENT_BUSY',
			'E_MODEL_INVALID',
			'E_INTERNAL',
		],
		bodySchema: createRunBodySchema,
		bodyKeys: CREATE_RUN_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/runs',
		auth: 'device',
		reqType: 'void',
		resType: 'ListRunsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/runs/:runId',
		auth: 'device',
		reqType: 'void',
		resType: 'GetRunResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/runs/:runId/abort',
		auth: 'device',
		reqType: 'AbortRunBody',
		resType: 'AbortRunResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_VALIDATION', 'E_INTERNAL'],
		bodySchema: abortRunBodySchema,
		bodyKeys: ABORT_RUN_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/runs/:runId/rerun',
		auth: 'device',
		reqType: 'RerunRunBody',
		resType: 'RerunRunResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_VALIDATION',
			'E_RUN_ALREADY_EXISTS',
			'E_SNAPSHOT_STALE',
			'E_AGENT_UNAVAILABLE',
			'E_INTERNAL',
		],
		bodySchema: rerunRunBodySchema,
		bodyKeys: RERUN_RUN_BODY_KEYS,
	},
	{
		method: 'POST',
		path: '/api/v1/runs/:runId/messages',
		auth: 'device',
		reqType: 'CreateRunMessageBody',
		resType: 'CreateRunMessageResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_VALIDATION',
			'E_MESSAGE_UNDELIVERED',
			'E_CAPABILITY_UNSUPPORTED',
			'E_INTERNAL',
		],
		bodySchema: createRunMessageBodySchema,
		bodyKeys: CREATE_RUN_MESSAGE_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/runs/:runId/log',
		auth: 'device',
		reqType: 'void',
		resType: 'GetRunLogResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_LOG_FILE_MISSING',
			'E_LOG_PURGED',
			'E_INTERNAL',
		],
	},
	{
		method: 'GET',
		path: '/api/v1/runs/:runId/search',
		auth: 'device',
		reqType: 'void',
		resType: 'SearchRunLogResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_LOG_FILE_MISSING',
			'E_LOG_PURGED',
			'E_INTERNAL',
		],
	},
	{
		method: 'DELETE',
		path: '/api/v1/runs/:runId/logs',
		auth: 'device',
		reqType: 'void',
		resType: 'PurgeRunLogsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_VALIDATION', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/tasks/:taskId/landing',
		auth: 'device',
		reqType: 'void',
		resType: 'GetTaskLandingResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/tasks/:taskId/worktree/cleanup',
		auth: 'device',
		reqType: 'void',
		resType: 'CleanupTaskWorktreeResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_NOT_FOUND', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/system/usage',
		auth: 'device',
		reqType: 'void',
		resType: 'SystemUsageResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/gates',
		auth: 'device',
		reqType: 'void',
		resType: 'ListGatesResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'POST',
		path: '/api/v1/gates/:gateId/decide',
		auth: 'device',
		reqType: 'DecideGateBody',
		resType: 'DecideGateResponse',
		errors: [
			'E_UNAUTHORIZED',
			'E_DEVICE_REVOKED',
			'E_NOT_FOUND',
			'E_VALIDATION',
			'E_GATE_ALREADY_DECIDED',
			'E_INTERNAL',
		],
		bodySchema: decideGateBodySchema,
		bodyKeys: DECIDE_GATE_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/settings/gates',
		auth: 'device',
		reqType: 'void',
		resType: 'UpdateGateSettingsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'PATCH',
		path: '/api/v1/settings/gates',
		auth: 'device',
		reqType: 'UpdateGateSettingsBody',
		resType: 'UpdateGateSettingsResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_VALIDATION', 'E_INTERNAL'],
		bodySchema: updateGateSettingsBodySchema,
		bodyKeys: UPDATE_GATE_SETTINGS_BODY_KEYS,
	},
	{
		method: 'GET',
		path: '/api/v1/snapshot',
		auth: 'device',
		reqType: 'void',
		resType: 'SnapshotResponse',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_INTERNAL'],
	},
	{
		method: 'GET',
		path: '/api/v1/events',
		auth: 'device',
		reqType: 'void',
		resType: 'text/event-stream',
		errors: ['E_UNAUTHORIZED', 'E_DEVICE_REVOKED', 'E_REPLAY_WINDOW_EXPIRED', 'E_INTERNAL'],
	},
] as const;
